/*
 * This file was generated by the mkbuiltins program.
 */

#include <sys/cdefs.h>
#define BLTINCMD 0
#define ALIASCMD 1
#define BGCMD 2
#define BINDCMD 3
#define BREAKCMD 4
#define CDCMD 5
#define COMMANDCMD 6
#define DOTCMD 7
#define ECHOCMD 8
#define EVALCMD 9
#define EXECCMD 10
#define EXITCMD 11
#define LETCMD 12
#define EXPORTCMD 13
#define FALSECMD 14
#define FGCMD 15
#define GETOPTSCMD 16
#define HASHCMD 17
#define HISTCMD 18
#define JOBIDCMD 19
#define JOBSCMD 20
#define KILLCMD 21
#define LOCALCMD 22
#define PRINTFCMD 23
#define PWDCMD 24
#define READCMD 25
#define RETURNCMD 26
#define SETCMD 27
#define SETVARCMD 28
#define SHIFTCMD 29
#define TESTCMD 30
#define TIMESCMD 31
#define TRAPCMD 32
#define TRUECMD 33
#define TYPECMD 34
#define ULIMITCMD 35
#define UMASKCMD 36
#define UNALIASCMD 37
#define UNSETCMD 38
#define WAITCMD 39
#define WORDEXPCMD 40

struct builtincmd
{
	const_cstring_t name;
	int32_t code;
	int32_t special;
};

extern int32_t (*const builtinfunc[])(int32_t, cstring_t*);
extern const struct builtincmd builtincmd[];

int32_t bltincmd(int32_t, cstring_t*);
int32_t aliascmd(int32_t, cstring_t*);
int32_t bgcmd(int32_t, cstring_t*);
int32_t bindcmd(int32_t, cstring_t*);
int32_t breakcmd(int32_t, cstring_t*);
int32_t cdcmd(int32_t, cstring_t*);
int32_t commandcmd(int32_t, cstring_t*);
int32_t dotcmd(int32_t, cstring_t*);
int32_t echocmd(int32_t, cstring_t*);
int32_t evalcmd(int32_t, cstring_t*);
int32_t execcmd(int32_t, cstring_t*);
int32_t exitcmd(int32_t, cstring_t*);
int32_t letcmd(int32_t, cstring_t*);
int32_t exportcmd(int32_t, cstring_t*);
int32_t falsecmd(int32_t, cstring_t*);
int32_t fgcmd(int32_t, cstring_t*);
int32_t getoptscmd(int32_t, cstring_t*);
int32_t hashcmd(int32_t, cstring_t*);
int32_t histcmd(int32_t, cstring_t*);
int32_t jobidcmd(int32_t, cstring_t*);
int32_t jobscmd(int32_t, cstring_t*);
int32_t killcmd(int32_t, cstring_t*);
int32_t localcmd(int32_t, cstring_t*);
int32_t printfcmd(int32_t, cstring_t*);
int32_t pwdcmd(int32_t, cstring_t*);
int32_t readcmd(int32_t, cstring_t*);
int32_t returncmd(int32_t, cstring_t*);
int32_t setcmd(int32_t, cstring_t*);
int32_t setvarcmd(int32_t, cstring_t*);
int32_t shiftcmd(int32_t, cstring_t*);
int32_t testcmd(int32_t, cstring_t*);
int32_t timescmd(int32_t, cstring_t*);
int32_t trapcmd(int32_t, cstring_t*);
int32_t truecmd(int32_t, cstring_t*);
int32_t typecmd(int32_t, cstring_t*);
int32_t ulimitcmd(int32_t, cstring_t*);
int32_t umaskcmd(int32_t, cstring_t*);
int32_t unaliascmd(int32_t, cstring_t*);
int32_t unsetcmd(int32_t, cstring_t*);
int32_t waitcmd(int32_t, cstring_t*);
int32_t wordexpcmd(int32_t, cstring_t*);
