/*
 * This file was generated by the mknodes program.
 */

#define NSEMI 0
#define NCMD 1
#define NPIPE 2
#define NREDIR 3
#define NBACKGND 4
#define NSUBSHELL 5
#define NAND 6
#define NOR 7
#define NIF 8
#define NWHILE 9
#define NUNTIL 10
#define NFOR 11
#define NCASE 12
#define NCLIST 13
#define NCLISTFALLTHRU 14
#define NDEFUN 15
#define NARG 16
#define NTO 17
#define NFROM 18
#define NFROMTO 19
#define NAPPEND 20
#define NCLOBBER 21
#define NTOFD 22
#define NFROMFD 23
#define NHERE 24
#define NXHERE 25
#define NNOT 26



struct nbinary
{
	int32_t type;
	union node* ch1;
	union node* ch2;
};


struct ncmd
{
	int32_t type;
	union node* args;
	union node* redirect;
};


struct npipe
{
	int32_t type;
	int32_t backgnd;
	struct nodelist* cmdlist;
};


struct nredir
{
	int32_t type;
	union node* n;
	union node* redirect;
};


struct nif
{
	int32_t type;
	union node* test;
	union node* ifpart;
	union node* elsepart;
};


struct nfor
{
	int32_t type;
	union node* args;
	union node* body;
	cstring_t var;
};


struct ncase
{
	int32_t type;
	union node* expr;
	union node* cases;
};


struct nclist
{
	int32_t type;
	union node* next;
	union node* pattern;
	union node* body;
};


struct narg
{
	int32_t type;
	union node* next;
	cstring_t text;
	struct nodelist* backquote;
};


struct nfile
{
	int32_t type;
	int32_t fd;
	union node* next;
	union node* fname;
	cstring_t expfname;
};


struct ndup
{
	int32_t type;
	int32_t fd;
	union node* next;
	int32_t dupfd;
	union node* vname;
};


struct nhere
{
	int32_t type;
	int32_t fd;
	union node* next;
	union node* doc;
	cstring_t expdoc;
};


struct nnot
{
	int32_t type;
	union node* com;
};


union node
{
	int32_t type;
	struct nbinary nbinary;
	struct ncmd ncmd;
	struct npipe npipe;
	struct nredir nredir;
	struct nif nif;
	struct nfor nfor;
	struct ncase ncase;
	struct nclist nclist;
	struct narg narg;
	struct nfile nfile;
	struct ndup ndup;
	struct nhere nhere;
	struct nnot nnot;
};


struct nodelist
{
	struct nodelist* next;
	union node* n;
};


struct funcdef;
struct funcdef* copyfunc(union node*);
union node* getfuncnode(struct funcdef*);
void reffunc(struct funcdef*);
void unreffunc(struct funcdef*);
